# Generated by Django 3.0.14 on 2022-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.TextField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi Mumbai', 'Navi Mumbai')], max_length=50)),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
    ]
