# Generated by Django 3.0.14 on 2022-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi Mumbai', 'Navi Mumbai')], max_length=50)),
            ],
        ),
    ]
