# Generated by Django 3.0.14 on 2022-01-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_companysignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=80)),
                ('company_name', models.TextField(max_length=80)),
            ],
        ),
    ]
