# Generated by Django 3.0.14 on 2022-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_addemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysignup',
            name='city',
            field=models.TextField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi Mumbai', 'Navi Mumbai')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companysignup',
            name='company_name',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='companysignup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
