# Generated by Django 3.0.14 on 2022-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_auto_20220106_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysignup',
            name='name',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
