# Generated by Django 3.0.14 on 2022-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0007_addemployees_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployees',
            name='updated_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
