# Generated by Django 3.0.14 on 2022-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0009_remove_addemployees_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployees',
            name='total_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
