# Generated by Django 3.0.14 on 2022-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0010_addemployees_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployees',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
