# Generated by Django 3.0.14 on 2022-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NeedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.TextField(max_length=50)),
            ],
        ),
    ]
