# Generated by Django 3.0.14 on 2022-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_for_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachcar',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Hatchbacks & sedans', 'Hatchbacks & sedans'), ('SUV', 'SUV'), ('Tempo travellers', 'Tempo travellers')], max_length=20, null=True),
        ),
    ]
