# Generated by Django 3.0.14 on 2022-01-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_citycab_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycab_reviews',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
