# Generated by Django 3.0.14 on 2022-01-04 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_citycab_reviews_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycab_reviews',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
