# Generated by Django 3.0.14 on 2022-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220104_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstationCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(blank=True, choices=[('Hatchbacks & sedans', 'Hatchbacks & sedans'), ('SUV', 'SUV'), ('Tempo travellers', 'Tempo travellers')], max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(default=0)),
                ('home_city', models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi Mumbai', 'Navi Mumbai')], max_length=20, null=True)),
                ('destination_city', models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi Mumbai', 'Navi Mumbai')], max_length=20, null=True)),
                ('no_of_passengers', models.CharField(blank=True, choices=[('1-4', '1-4'), ('4-7', '4-7'), ('7-16', '7-16')], max_length=5, null=True)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('categoryname', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
