# Generated by Django 3.0.14 on 2022-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_outstationcab'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
