# Generated by Django 3.0.14 on 2022-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
