# Generated by Django 3.0.14 on 2022-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customer_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycab',
            name='date',
        ),
        migrations.RemoveField(
            model_name='citycab',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='citycab',
            name='drop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citycab',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
