# Generated by Django 3.0.14 on 2022-01-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220106_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycab',
            name='drop_time',
        ),
        migrations.CreateModel(
            name='CityCabBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Customer')),
            ],
        ),
    ]
