# Generated by Django 3.0.14 on 2022-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_filteringhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteringhistory',
            name='pickup_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
