# Generated by Django 3.0.14 on 2022-01-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220106_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycabbooking',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
