# Generated by Django 3.0.14 on 2022-01-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_citycabbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
