# Generated by Django 3.0.14 on 2022-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customer_updated_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
