# Generated by Django 3.0.14 on 2022-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_customer_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycabbooking',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
