# Generated by Django 3.0.14 on 2022-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_citycabbooking_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycabbooking',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
